Shop.WebUI/Models/CatalogListModel.cs
using Shop.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.Models
{
    public class CatalogListModel
    {
        public List<Product> Products { get; set; }
        public List<Category> Categories { get; set; }
    }
}

Shop.WebUI/Models/ProductCreateModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Shop.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.WebUI.Models
{
    public class ProductCreateModel
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage="Zorunlu")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Zorunlu")]
        public double Price { get; set; }
        [Required(ErrorMessage = "Zorunlu")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Zorunlu")]
        public int SelectedCategoryId { get; set; }
    }



}

Shop.WebUI/Models/ProductImagesModel.cs
using Shop.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.Models
{
    public class ProductImagesModel
    {
        public Product Product { get; set; }
        public List<Image> Images { get; set; }

    }
}

Shop.WebUI/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Business.Abstract;
using Shop.Entities;
using Shop.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private IUnitOfWork unitOfWork;

        public CategoryController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IActionResult Index()
        {
            var model = new CatalogListModel()
            {
                Categories = unitOfWork.Categories.GetAll().ToList(),
                Products = unitOfWork.Products.GetAll().ToList()
            };

            return View(model);    
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Categories.Add(category);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(unitOfWork.Categories.Get(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Deleted(Category category)
        {
            unitOfWork.Categories.Delete(category);
            unitOfWork.SaveChanges();
            TempData["message"] = "Deleted";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(unitOfWork.Categories.Get(id));
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Categories.Edit(category);
                unitOfWork.SaveChanges();

                TempData["message"] = $"{ category.CategoryName} is updated.";
                return RedirectToAction("Index");
            }
            return View(category);
        }


    }
}

Shop.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Business.Abstract;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IProductService productService;

        public HomeController(IProductService _productService)
        {
            productService = _productService;
        }
        public IActionResult Index(int? id)
        {
            if (id == null)
            {
                return View(productService.GetAll());

            }
            else
            {
                var condition = productService.GetAll().Where(i => i.CategoryId == id);
                return View(condition);
            }
        }



    }
}

Shop.WebUI/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shop.Business.Abstract;
using Shop.Entities;
using Shop.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IUnitOfWork unitOfWork;
        private readonly IMapper mapper; // AutoMapper

        public ProductController(IUnitOfWork _unitOfWork,IMapper _mapper)
        {
            unitOfWork = _unitOfWork;
            mapper = _mapper;
        }
        public IActionResult Index()
        {
            var model = new CatalogListModel()
            {
                Categories = unitOfWork.Categories.GetAll().ToList(),
                Products = unitOfWork.Products.GetAll().ToList()
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            
            ViewBag.AllCategories = new SelectList(unitOfWork.Categories.GetAll(), "CategoryId", "CategoryName");

            var emptyViewModel = new ProductCreateModel();
            return View(emptyViewModel);
        }

        [HttpPost]
        public IActionResult Create(ProductCreateModel model)
        {
            /* add new product */

            if (ModelState.IsValid)
            {
                Product product = mapper.Map<Product>(model);

                unitOfWork.Products.Add(product);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.AllCategories = new SelectList(unitOfWork.Categories.GetAll(), "CategoryId", "CategoryName");

                return View(model);
            }
            

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(unitOfWork.Products.Get(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Deleted(Product product)
        {
            unitOfWork.Products.Delete(product);
            unitOfWork.SaveChanges();
            TempData["message"] = "Deleted";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(unitOfWork.Categories.GetAll(), "CategoryId", "CategoryName");

            return View(unitOfWork.Products.Get((int)id));
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Products.Edit(product);
                unitOfWork.SaveChanges();

                TempData["message"] = $"{ product.ProductName} is updated.";
                return RedirectToAction("Index");
            }
            ViewBag.Categories = new SelectList(unitOfWork.Categories.GetAll(), "CategoryId", "CategoryName");
            return View(product);
        }



        [HttpGet]
        public IActionResult Detail(int id)
        {
            var model = new ProductImagesModel()
            {
                Images = unitOfWork.Images.GetImagesByProduct(id),
                Product = unitOfWork.Products.Get(id)
            };
            return View(model);
        }
    }
}

Shop.WebUI/ViewComponents/LeftSideMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Business.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.WebUI.ViewComponents
{
    public class LeftSideMenuViewComponent : ViewComponent
    {
        private IUnitOfWork unitOfWork;

        public LeftSideMenuViewComponent(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IViewComponentResult Invoke()
        {
            return View(unitOfWork.Categories.GetAll());
        }
    }
}

Shop.WebUI/Views/Category/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <h3 class="mt-5 mb-5">Create Category</h3>
    <form asp-action="Create" asp-controller="Category" method="post">
        <div class="mb-3">
            <label asp-for="CategoryName" class="form-label">Category Name</label>
            <input asp-for="CategoryName" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

Shop.WebUI/Views/Category/Delete.cshtml
@model Category
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="container mt-5">
    <h4>
        Do you want to delete <b>@Model.CategoryName</b>?
    </h4>

    <form asp-controller="Category" asp-action="Delete" method="post">
        <input type="hidden" asp-for="CategoryId" />
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>

Shop.WebUI/Views/Category/Edit.cshtml
@model Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <h3 class="mt-5 mb-5">Update Category</h3>
    <form asp-action="Edit" asp-controller="Category" method="post" asp-route-id="@Model.CategoryId">
        <!--category id yi tutmak çok önemli update işleminde-->
        <input type="hidden" asp-for="CategoryId" />
        <div class="mb-3">
            <label asp-for="CategoryName" class="form-label">Category Name</label>
            <input asp-for="CategoryName" class="form-control">
        </div>
        <button type="submit" class="btn btn-dark">Edit</button>
    </form>
</div>

Shop.WebUI/Views/Category/Index.cshtml
@model CatalogListModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">

    <div class="card">
        <div class="card-header">
            Categories
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Category Name</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Categories)
                    {
                        <tr>
                            <th>@item.CategoryId</th>
                            <td>@item.CategoryName</td>
                            <td>

                                <a class="btn btn-primary btn-sm" asp-action="Edit" asp-controller="Category" asp-route-id="@item.CategoryId">Edit</a>
                                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="Category" asp-route-id="@item.CategoryId">Delete</a>


                            </td>
                        </tr>
                    }


                </tbody>
            </table>
            <div class="card-footer">

                <a class="btn btn-primary btn-sm" asp-action="Create" asp-controller="Category">Create</a>


            </div>
        </div>
    </div>

</div>

Shop.WebUI/Views/Home/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Carousel Part-->
<div id="slider">
    <figure>
        <img src="~/myTheme/images/carousel1.png" alt="">
        <img src="~/myTheme/images/carousel2.png" alt="">
        <img src="~/myTheme/images/carousel3.png" alt="">
    </figure>
</div>

<div class="container pb-2 mt-5 list-product">

    <div class="row row-list">
        <div class="col-md-2">
            @await Component.InvokeAsync("LeftSideMenu")
        </div>

        <div class="col-md-10">
            <div class="row row-cols-1 row-cols-md-4 g-4">
                @Html.Partial("_ProductList", Model)
            </div>
        </div>
    </div>
</div>

Shop.WebUI/Views/Product/Create.cshtml
@model ProductCreateModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-5">
    <h3 class="mb-3">Create Product</h3>
    <form asp-action="Create" asp-controller="Product" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="@Model.ProductName" class="form-label">Product Name</label>
            <input asp-for="@Model.ProductName" class="form-control">
            <span asp-validation-for="@Model.ProductName"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price" class="form-label">Price</label>
            <input asp-for="@Model.Price" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description" class="form-label">Description</label>
            <input asp-for="@Model.Description" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.SelectedCategoryId" class="mb-3 mt-3">Select Category</label>
            <select class="form-control" asp-for="@Model.SelectedCategoryId" asp-items="ViewBag.AllCategories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button type="submit" class="btn btn-dark mt-5">Create</button>
    </form>
</div>

Shop.WebUI/Views/Product/Delete.cshtml
@model Product
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="container mt-5">
    <h4>
        Do you want to delete <b>@Model.ProductName</b>?
    </h4>

    <form asp-controller="Product" asp-action="Delete" method="post">
        <input type="hidden" asp-for="ProductId" />
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>

Shop.WebUI/Views/Product/Detail.cshtml
@model ProductImagesModel
@{
    ViewData["Title"] = "Detail";
}


<div class="container mt-5">
    <div class="smallcontainer single-product">
        <div class="row">
            <div class="col-2">

                <img src="~/images/kafkaokur.jpg" width="100%" id="productImg" alt="" data-bs-toggle="modal" data-bs-target="#largeModal">
                <div class="small-img-row">

                    @foreach (var item in Model.Images)
                    {
                        <div class="small-img-col">
                            <img src="~/images/@item.ImageURL" width="100%" class="small-img" alt="">
                        </div>
                    }


                </div>
            </div>
            <div class="col-2">

                <h1>@Model.Product.ProductName</h1>
                <h4>$@Model.Product.Price</h4>
                <input type="number" value="1">
                <a asp-action="AddToCart" asp-controller="Product" class="cart-btn"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
                <br>
                <h4>İçerik</h4>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis laudantium fugiat voluptates, minima obcaecati minus suscipit placeat consectetur labore dignissimos impedit et vero libero id?</p>
            </div>
        </div>
    </div>

    <!-- Bu kısmı hazır bir template üzerinde değişiklik yaparak oluşturdum -->
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <!-- carousel -->
                    <div id='carouselExampleIndicators'
                         class='carousel slide'
                         data-ride='carousel'>
                        <ol class='carousel-indicators'>
                            <li data-target='#carouselExampleIndicators'
                                data-slide-to='0'
                                class='active'></li>
                            <li data-target='#carouselExampleIndicators'
                                data-slide-to='1'></li>
                            <li data-target='#carouselExampleIndicators'
                                data-slide-to='2'></li>
                        </ol>
                        <div class='carousel-inner'>
                            <div class='carousel-item active'>
                                <img class='slideImg-size' src='~/images/kafkaokur.jpg' alt='First slide' />
                            </div>
                            <div class='carousel-item'>
                                <img class='slideImg-size' src='~/images/kafkaokur.jpg' alt='Second slide' />
                            </div>
                            <div class='carousel-item'>
                                <img class='slideImg-size' src='~/images/kafkaokur.jpg' alt='Second slide' />
                            </div>
                        </div>
                        <a class='carousel-control-prev'
                           href='#carouselExampleIndicators'
                           role='button'
                           data-slide='prev'>
                            <span class='carousel-control-prev-icon'
                                  aria-hidden='true'></span>
                            <span class='sr-only'>Previous</span>
                        </a>
                        <a class='carousel-control-next'
                           href='#carouselExampleIndicators'
                           role='button'
                           data-slide='next'>
                            <span class='carousel-control-next-icon'
                                  aria-hidden='true'></span>
                            <span class='sr-only'>Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

Shop.WebUI/Views/Product/Edit.cshtml
@model Product
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="container mt-5">
    <h3 class="mb-3">Edit Product</h3>
    <form asp-action="Edit" asp-controller="Product" method="post">


        <!--
        Create işleminde bunu yapmadık primary key olduğu için otomatik kendisi alıyor.
        Ancak update işleminde hangi ürünü update ettiğimizi belirtiyoruz.
        Bu bilgiyi kullanıcının bilmesine gerek yok o yüzden type=hidden
    -->
        <input type="hidden" asp-for="ProductId" />
        <div class="mb-3">
            <label asp-for="ProductName" class="form-label">Product Name</label>
            <input asp-for="ProductName" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Price" class="form-label">Price</label>
            <input asp-for="Price" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" class="form-control">
        </div>

        <div class="form-group">
            <label asp-for="Category" class="mb-3"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories" required>
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button type="submit" class="btn btn-dark mt-5 mb-5">Update</button>
    </form>
</div>

Shop.WebUI/Views/Product/Index.cshtml
@model CatalogListModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Ürünler
        </div>
        <div class="card-body">
            @if (Model.Products.Count() > 0)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Description</th>
                            <th>Category Name</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Products)
                        {
                        <tr>
                            <th>@item.ProductId</th>
                            <!--Resimleri unutma-->
                            <td>@item.ProductName</td>
                            <td>@item.Price</td>
                            <td>@item.Description</td>
                            <td>@item.Category.CategoryName</td>

                            <td>
                                <a class="btn btn-primary btn-sm" asp-action="Edit" asp-controller="Product" asp-route-id="@item.ProductId">Update</a>
                                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="Product" asp-route-id="@item.ProductId">Delete</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                <div class="card-footer">
                    <a class="btn btn-primary btn-sm" asp-action="Create" asp-controller="Product">Create</a>

                </div>
            }
            else
            {
                <div class="alert alert-danger">
                    Stokta ürün yok
                </div>
            }
        </div>
    </div>
</div>

Shop.WebUI/Views/Shared/Components/LeftSideMenu/Default.cshtml
<!--Burada category menu partial olarak tutuluyor.Default dışında farklı stylelara sahip menüler oluşturulabilir-->

@model IEnumerable<Category>

<ul class="list-group">

    @foreach (var item in Model)
    {
        /*Eğer itemin category id'si seçilen kategori ile aynı ise o kategori active classına sahip olacak*/
        <a asp-controller="Home" asp-action="Index" asp-route-id="@item.CategoryId" 
           class="list-group-item  @(ViewBag.SelectedCategory==item.CategoryId.ToString() ? "active special-color":"")">
            @item.CategoryName
        </a>
    }


</ul>

Shop.WebUI/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="~/myTheme/css/main.css">
    <link rel="stylesheet" href="~/myTheme/css/admin-style.css">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <title>R's Shop</title>
    <link rel="icon" href="~/myTheme/images/iconR-removebg-preview.png">

</head>
<body>
    <!-- Header -->
    <header>
        <div class="container">
            <nav id="navbar">
                <h1 class="logo">Admin Panel</h1>
                <ul>
                    <li><a asp-action="Index" asp-controller="Category">Categories</a></li>
                    <li><a asp-action="Index" asp-controller="Product">Products</a></li>
                </ul>
            </nav>
            <hr />
        </div>
    </header>


    <div>
        <div class="container mt-5">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">
                    @TempData["message"]
                </div>
            }
        </div>
        @RenderBody()
    </div>


    <script src="~/myTheme/js/app.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

Shop.WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link href="~/myTheme/css/main.css" rel="stylesheet" />
    <title>R's Shop</title>
    <link rel="icon" href="~/myTheme/images/iconR-removebg-preview.png">

</head>
<body>
    <!-- Header -->
    <header>
        <div class="container">
            <nav id="navbar">
                <h1 class="logo">R's Shop</h1>
                <ul>
                    <li><a href="#">Fırsat</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Admin</a></li>
                    <li><a href="#">Sepetim</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!--
        Categorynavbar : Bu navbar diğer websitelerdeki gibi statik bir navbar ve En popular olanlar gibi düşünüldü.
    -->

    <nav id="navbar" class="category-navbar">
        <ul>
            <li><a href="#">Kitap</a></li>
            <li><a href="#">Kırtasiye</a></li>
            <li><a href="#">Dergi</a></li>
            <li><a href="#">Çocuk Kitapları</a></li>
            <li><a href="#">Elektronik</a></li>
            <li><a href="#">Oyuncak</a></li>
        </ul>
    </nav>

    <div id="main">

        @RenderBody()
    </div>

    <!-- Footer -->
    <div class="container mt-5">
        <footer class="mt-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Privacy</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">© 2021 R's Store Company</p>
        </footer>
    </div>

    <script src="~/myTheme/js/app.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</body>
</html>

Shop.WebUI/Views/Shared/_ProductList.cshtml
@model IEnumerable<Product>


@if (Model.Count() == 0)
{
    <div class="alert alert-warning">
        There is no product
    </div>
}
else
{
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card h-100 card-img-top">
                

                <div class="card-body">
                    <h5 class="card-title">@item.ProductName</h5>
                    <h4 class="card-text">$@item.Price</h4>
                </div>
                <div class="card-footer">
                    <a class="btn btn-dark btn-sm" asp-controller="Product" asp-action="Detail" asp-route-id="@item.ProductId">Details</a>
                    <a class="btn home-cart-button btn-sm" asp-controller="Product" asp-action="AddToCart" asp-route-id="@item.ProductId">Add To Cart</a>

                </div>
            </div>
        </div>
    }
}